# This workflow will build the project, run tests and collect test coverage,
# add coverage report for pull requests or create a coverage badge for the default branch.

name: coverage
on: [push, pull_request]
jobs:
  collect-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET of required version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Run tests and collect test coverage
        run: dotnet test src/Lambdy.sln /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      - name: Display test coverage
        uses: ewjoachim/coverage-comment-action@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_FILE: "src/Lambdy.Tests/coverage.cobertura.xml"
          BADGE_ENABLED: "true"
          BADGE_FILENAME: test-coverage-badge.json
          MINIMUM_GREEN: 80
          MINIMUM_ORANGE: 50
