# This workflow will check the quality of code using several analyzers.

name: lint
on: [push, pull_request]
jobs:
  check-with-fantomas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET of required version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Restore required tools
        run: dotnet tool restore
      - name: Check with fantomas
        run: dotnet fantomas --verbosity d --check src
